Crypto101.org
=> added AES key schedule

Crypto101.org
=> Typo fix: "atechnical" -> "non-technical"

Crypto101.org
Added the steps for the Authenticated Key Exchange. I also turned the AKE section into a "subchapter"
=> Add OTR AKE chapter and all its steps

Crypto101.org
These are just minor fixes to spacing around ellipses.
=> Ellipses fixes

Crypto101.org
In my previous patch I accidentally removed a space, this patch adds it
back.
Sorry about that, don't know how this happened.
=> Section 9.2: Add missing space back.

Crypto101.bib, Crypto101.org
I made a mess of the previous pull request, so I created a new one.
=> Write about SHA-1 hash function - v.2

Crypto101.bib, Crypto101.org
Here's the chapter on SHA-2. I am looking forward to your feedback and ideas.
=> Write about the SHA-2 family.

Crypto101.org
I have started writing about ARX as suggested in issue #297. I hope to go into more detail and demonstrate its use in an equation.
Wishing you a merry Christmas. 🎅🎄🎁⛄
=> Write about ARX.

Crypto101.bib, Crypto101.org
I am looking forward to your feedback.
=> Write about Keccak and SHA-3

Crypto101.bib, Crypto101.org
Added a reference to the first SHA-1 collision.
=> Update SHA-1 chapter.

Crypto101.org
=> Change "there's" to "there are" when plural

.travis.yml, README.rst
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
WIP https://travis-ci.com/gliptak/book/builds/101868078
Would you have some pointers on how to correct
```
Unknown LaTeX class `per-file-class'
Makefile:21: recipe for target 'Crypto101.tex' failed
```
https://github.com/crypto101/book/issues/263
=> Add Travis build

.travis.yml, Dockerfile
https://github.com/crypto101/book/issues/263
=> Separate Dockerfile

Dockerfile
Changes are not functional, but purely formatting-related. See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run for description and reasoning.
=> Follow Dockerfile best practices

src/glossary.rst
=> glossary: s/real-live/real-life/

Makefile, src/conf.py, src/subfig.py
I noticed some parts of the content's translation wouldn't go through, so here are the fixes
=> various i18n fixes

src/Crypto101.bib
https://github.com/crypto101/book/issues/381
=> Commented unreferenced entries

src/exclusive-or.rst
Smaller portions reviewed for [PR383](https://github.com/crypto101/book/pull/383)
I added some inline feedback on above link where I could contribute
=> Smaller bites of PR383 of crypto101/book

src/exclusive-or.rst
Smaller portions reviewed for [PR384](https://github.com/crypto101/book/pull/384)
I added some inline feedback on above link where I could contribute
=> Smaller bites reviewed for PR384

src/stream-ciphers.rst
Updated to fix where [PR-386](https://github.com/crypto101/book/pull/386) changes crypto meanings
=> Reviewed PR-386

src/stream-ciphers.rst
=> Proof-read PR387

docker/Dockerfile.fedora
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Bump Fedora to 34 in Dockerfile

.github/workflows/ci.yml, src/conf.py
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://github.com/gliptak/book/actions/runs/959062645
https://github.com/actions/runner/issues/241
https://github.com/crypto101/book/pull/416
=> Add Github Actions build

src/foreword.rst
Feel free to completely disregard, but IMO this is slightly easier to understand. I had to reread this sentence a few times when I came across it.
Also I would suggest replacing 
"Of course, if I never hear about your issue, it's very hard for me to address..." 
on lines 89-90 with 
"If you would like to make a suggestion, clarification, or correction, please \<action>." 
with \<action> being \<submit a pull request> or <email address@domain.com>.
The current wording *could* come across as passive aggressive, and a more direct call to action could help you with organization / process management.
Again, feel free to disregard, these are just some idle thoughts I had.
Thanks!
=> Reword "Development" in foreword.rst

docker/Dockerfile.fedora, docker/Dockerfile.ubuntu
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Correct build failure

docker/Dockerfile.ubuntu, src/conf.py
=> Bump Ubuntu to 22.04 for Docker
